#!/bin/lua
--[[
#=================================================
# Author  : Zvonimir Kucis
#=================================================
]]

conky.config = {

	--Various settings

	background = true,
	cpu_avg_samples = 2,
	diskio_avg_samples = 10,
	double_buffer = true,
	if_up_strictness = 'address',
	net_avg_samples = 2,
	no_buffers = true,
	temperature_unit = 'celsius',
	update_interval = 1,
	imlib_cache_size = 0,

	--Placement

	alignment = 'top_left',
	gap_x = 10,
	gap_y = 45,
	minimum_height = 1080,
	minimum_width = 280,
	maximum_width = 280,

	--Graphical

	border_inner_margin = 10,
	border_outer_margin = 10,
	draw_borders = false,
	draw_graph_borders = true,
	draw_shades = false,
	draw_outline = false,

	--Textual
	
	format_human_readable = true,
	font = 'JetBrainsMono Nerd Font Mono:size=6:bold',
	max_text_width = 0,
	short_units = true,
	use_xft = true,
	xftalpha = 1,

	--Windows

	own_window = true,
  own_window_class = 'Conky',
  own_window_type = 'override',
	own_window_argb_value = 0,
	own_window_argb_visual = true,
	

	--Colours

	default_color = '#000000',  				-- default color and border color
	color1 =     '#3851FF', 						-- title_color
	color2 =     '#CA00A6',						    -- top memory or processe, graphs
	color3 =     '#FF80FF',						    -- text color
  color4 = '#FF80FF'
};


conky.text = [[
#------------+
# INFO
#------------+
${color1}${font :size=14:bold}INFO ${hr 2}${font}
${voffset 5}${color1}OS :$alignr${color3}${execi 6000 lsb_release -d | grep 'Descr'|awk {'print $2 " " $3" " $4" " $5'}}
${voffset 2}${color1}Kernel :$alignr${color3} $kernel
${voffset 2}${color1}Uptime :$alignr${color3} $uptime
#------------+
#CPU
#------------+
${voffset 10}${color1}${font :size=14:bold}CPU ${hr 2}${font}
${voffset 5}${color1}Name : ${color3}$alignr${execi 6000 cat /proc/cpuinfo | grep 'model name' | sed -e 's/model name.*: //'| uniq | cut -c 1-16}
${voffset 2}${color1}Freq : ${color3}${freq_g} GHz$alignr${color1}Usage : ${color3}${cpu}%
#------------+
#CPU CORES
#------------+
${voffset 10}${color1}CPU CORES ${stippled_hr 3 3}
${voffset 5}${color1} 1${goto 45}${color3}${cpu cpu1}%${goto 85}${color2}${cpubar cpu1 13, 60}${goto 170}${color1} 2${goto 195}${color3}${cpu cpu2}%${goto 235}${color2}${cpubar cpu2 13, 60}
${voffset 2}${color1} 3${goto 45}${color3}${cpu cpu3}%${goto 85}${color2}${cpubar cpu3 13, 60}${goto 170}${color1} 4${goto 195}${color3}${cpu cpu4}%${goto 235}${color2}${cpubar cpu4 13, 60}
${voffset 2}${color1} 5${goto 45}${color3}${cpu cpu5}%${goto 85}${color2}${cpubar cpu5 13, 60}${goto 170}${color1} 6${goto 195}${color3}${cpu cpu6}%${goto 235}${color2}${cpubar cpu6 13, 60}
#------------+
#TEMPS
#------------+
${voffset 10}${color1}${font :size=14:bold}TEMPS ${hr 2}${font}
${voffset 5}${color1}CPU : ${color3}${execi 5 sensors | grep Tdie: | cut -c 16-19}°C$alignr${color1}NVME : ${color3}${execi 5 nvme smart-log /dev/nvme0n1 | grep '^temperature' | cut -d ":" -f 2 | cut -d " " -f 2}°C
#------------+
# PROCESSES
#------------+
${voffset 10}${color1}${font :size=14:bold}PROCESSES ${hr 2}${font}
${voffset 5}${color1}Name${goto 180}CPU%${alignr}MEM%
${color2}${top name 1} ${goto 180}${top cpu 1}${alignr}${top mem 1}${color3}
${top name 2} ${goto 180}${top cpu 2}${alignr}${top mem 2}
${top name 3} ${goto 180}${top cpu 3}${alignr}${top mem 3}
${top name 4} ${goto 180}${top cpu 4}${alignr}${top mem 4}
${top name 5} ${goto 180}${top cpu 5}${alignr}${top mem 5}
#------------+
# MEMORY
#------------+
${voffset 10}${color1}${font :size=14:bold}MEMORY ${hr 2}${font}
${voffset 5}${color1}Used: ${color3}$mem ($memperc%)${color1}${alignr}Free: ${color3}$memeasyfree
${color4}${membar}
${voffset 5}${color1}Name${goto 180}MEM%${alignr}MEM
${color2}${top_mem name 1} ${goto 180}${top_mem mem 1}${alignr}${top_mem mem_res 1}${color3}
${top_mem name 2} ${goto 180}${top_mem mem 2}${alignr}${top_mem mem_res 2}
${top_mem name 3} ${goto 180}${top_mem mem 3}${alignr}${top_mem mem_res 3}
${top_mem name 4} ${goto 180}${top_mem mem 4}${alignr}${top_mem mem_res 4}
${top_mem name 5} ${goto 180}${top_mem mem 5}${alignr}${top_mem mem_res 5}
#------------+
# DISK
#------------+
${voffset 10}${color1}${font :size=14:bold}DISK ${hr 2}${font}
# NVME
${voffset 5}${color1}NVME ${stippled_hr 3 3}
${voffset 5}${color1}Used: ${color3}${fs_used /}${color1}${goto 200}Free:${goto 250}${color3}${fs_free /}
${color2}${fs_bar /}
${voffset 2}${color1}Read: ${color3}${diskio_read nvme0n1}${goto 200}${color1}Write:${goto 250}${color3}${diskio_write nvme0n1}
${color4}${diskiograph_read nvme0n1 40,130} ${alignr}${diskiograph_write nvme0n1 40,130}
# HDD
#${voffset 7}${color1}HDD ${stippled_hr 3 3}
#${voffset 5}${color1}Used: ${color3}${fs_used /media/zkucis/HDD}${color1}${goto 200}Free:${goto 250}${color3}${fs_free /media/zkucis/HDD}
#${color2}${fs_bar /media/zkucis/HDD}
#${voffset 2}${color1}Read: ${color3}${diskio_read /dev/sda1}${goto 200}${color1}Write:${goto 250}${color3}${diskio_write /dev/sda1}
#${color2}${diskiograph_read /dev/sda1 40,130} ${alignr}${diskiograph_write /dev/sda1 40,130}

#------------+
# NETWORK
#------------+
${voffset 10}${color1}${font :size=14:bold}NETWORK ${hr 2}${font}
${voffset 5}${color3}Up: ${upspeedf wlan0} KiB/s${alignr}Down: ${downspeedf wlan0} KiB/s
${color4}${upspeedgraph wlan0 40,130 -l}$alignr${downspeedgraph wlan0 40, 130 -l}
#------------+
]]
